### ISSUE TITLE
Thumbnailer return JSON error instead of image

### ISSUE THREAD

**Issue by joshuaavalon** [directus/docker#10]
# Bug Report

## Steps to Reproduce

1. Create a collection with a file field
2. Upload an image
3. Go back to collection page

## Expected Behavior

Show thumbnail.

## Actual Behavior
Status code 404

```json
{"error":{"error":8,"message":"API Environment Configuration Not Found: thumbnail"}}
```

## Other Context & Screenshots

![directus](https://user-images.githubusercontent.com/7152420/49518604-ffeb4300-f8d9-11e8-995c-4f884f5ffd99.PNG)

The original image is fine. Only thumbnail is having problem.

## Technical Details

[**docker-compose.yml**](https://github.com/directus/docker/blob/e586fe0f124612deccf4176d3ca6e2b012ed94b5/examples/single-api/docker-compose.yml) from example
```yaml
version: "3"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "somedb"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "someusername"
      MYSQL_PASSWORD: "somepassword"
    ports:
      - 3306:3306

  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: "somedb"
      DATABASE_USERNAME: "someusername"
      DATABASE_PASSWORD: "somepassword"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directusrocks"
    ports:
      - 7000:80

  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://localhost:7000/_/"
    ports:
      - 8000:80
```
