### ISSUE TITLE
Cannot upload files (Max Size: 0B)

### ISSUE THREAD

**Issue by joshuaavalon** [directus/docker#14]
**docker-compose.yml**
```yml
version: "3"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "somedb"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "someusername"
      MYSQL_PASSWORD: "somepassword"
    ports:
      - 3306:3306
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: "somedb"
      DATABASE_USERNAME: "someusername"
      DATABASE_PASSWORD: "somepassword"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directusrocks"
    ports:
      - 7000:80
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://192.168.1.187:7000/_/"
    ports:
      - 8000:80
```

If I send a get request to `http://192.168.1.187:7000/_/`, I get
```json
{
  "data": {
    "api": {
      "version": "2.0.13",
      "database": "mysql"
    },
    "server": {
      "max_upload_size": 2097152,
      "general": {
        "php_version": "7.2.13",
        "php_api": "fpm-fcgi"
      }
    }
  }
}
```

However,

![directus](https://user-images.githubusercontent.com/7152420/50562720-6cc6f100-0d51-11e9-8037-8d2af467d661.PNG)

Potential problem(?)

There are two errors in network tab.

1. OPTIONS 405 on `http://192.168.1.187:7000/`
My guess is it should be `http://192.168.1.187:7000/_/` instead. There is some error on rewrite which make the app cannot get configuration.

2. GET 500 on `http://192.168.1.187:7000/_/users/me?fields=last_page`
I don't think this is the problem.
