### ISSUE TITLE
Docker setup: nginx respond 405 on authentication

### ISSUE THREAD

**Issue by bonaccorsop** [directus/docker#19]
This is my current docker-compose file:

```
version: "3"

services:

  #
  # API
  #
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: "mysql-external-host:3306"
      DATABASE_NAME: "directus"
      DATABASE_USERNAME: "mysqlusr"
      DATABASE_PASSWORD: "mysqlpass"
      ADMIN_EMAIL: "mysticuser@email.com"
      ADMIN_PASSWORD: "password"
    ports:
      - 30030:80

  #
  # Dashboard
  #
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "http://api:80"
    ports:
      - 30031:80
```

accessing at http://localhost:30031/#/login and typing my credentials I obtain a 405 nginx error:

![schermata 2019-01-22 alle 18 01 10](https://user-images.githubusercontent.com/539257/51552178-50aa0180-1e70-11e9-92bb-cb8c1493e1c6.png)

![schermata 2019-01-22 alle 18 01 15](https://user-images.githubusercontent.com/539257/51552193-57d10f80-1e70-11e9-8e76-3c7d93001838.png)

**Comment by rijkvanzanten** [comment]
No worries! I'll transfer it over.

**Comment by WoLfulus** [comment]
I think you're setting the APP environment variables to a wrong format.

```
      API_ENDPOINT: "http://api:80"
```

can you try changing the above to and see what happens?

```
      API_ENDPOINT: "API; http://localhost:30030/_/"
```

**Comment by am-webdev** [comment]
Hi @WoLfulus 

I'm running into the same issue but updating the API_ENDPOINT value results in 

I published the port to 7000:7000 on the API container
Another error GET http://localhost:7000/server/ping net::ERR_CONNECTION_REFUSED

In my setup I've got an reverse proxy and each container has its own dns sub domain

api.mytld.com and dashboard.mytlt.com

but either the login fails or the the API is not reachable. Any hints? I'm pretty sure I've made some configuration mistake.

Best regards

**Comment by mvhirsch** [comment]
Hi @am-webdev 

> I'm running into the same issue but updating the API_ENDPOINT value results in another error
> GET http://localhost:7000/server/ping net::ERR_CONNECTION_REFUSED

I don't think you're running in this particular issue from @bonaccorsop. Your error is `ERR_CONNECTION_REFUSED` (TCP) instead of `Method Not Allowed` (HTTP).

> I published the port to 7000:7000 on the API container, [...]

Here I spot a mistake, please refer to the docker documentation about mapping ports.
You probably wanted to map your local's host port 7000 to the container ones exposing at 80. Neither `directus/api` nor the `directus/app` are exposing any ports other than 80. So there is simply nothing that listens on the containers port 7000, which results in a refused connection.

So you should modify your setup like this: 

```
ports: 
    7000:80
````

**Comment by am-webdev** [comment]
Hi @mvhirsch 

> So you should modify your setup like this:

awesome :D that was my mistake. Thank you very much. As expected it was a layer 8 issue :D

Based on the reverse proxy setup, I've changed the published ports to
```
ports:
   - 80
```

So the reverse proxy knows the internal port e.g. 32856 and redirects the ports correctly. So for any interested people here's my working compose file with Nginx as a reverse proxy and lets encrypt auto renewal and two separated sub domains with a pre existing docker network.

```
version: "3"
services:
  # Directus Database
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "directusdb"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "directusdbuser"
      MYSQL_PASSWORD: ""
  # API
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: "directusdb"
      DATABASE_USERNAME: "directusdbuser"
      DATABASE_PASSWORD: ""
      ADMIN_EMAIL: ""
      ADMIN_PASSWORD: ""
      VIRTUAL_HOST: api.example.com
      LETSENCRYPT_HOST: api.example.com
      LETSENCRYPT_EMAIL: hello@example.com
      CORS_MAX_AGE: 500
    ports:
      - 80
  # Dashboard
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; https://api.example.com/_/"
      VIRTUAL_HOST: directus.example.com
      LETSENCRYPT_HOST: directus.example.com
      LETSENCRYPT_EMAIL: hello@example.com
      ALLOW_OTHER_API: "true"
    ports:
      - 80
networks:
  default:
    external:
      name: webproxy
```
