### ISSUE TITLE
Local database cannot be discovered

### ISSUE THREAD

**Issue by kurnifamili** [directus/docker#27]
Hi, I have a problem when I run `docker-compose up` with the following `docker-compose.yml`.
```
version: "3"
services:
  #
  # API
  #
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: localhost
      DATABASE_NAME: "mydb"
      DATABASE_USERNAME: "mydb"
      DATABASE_PASSWORD: "mydb"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directusrocks"
    ports:
      - 7000:80

  #
  # Dashboard
  #
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://localhost:7000/_/"
    ports:
      - 8000:80
```

I just copy-pasted this from the single-api example and removed the database part. But my local database cannot seem to be discovered even though it is definitely up. It's always stuck in `api_1  | nginx: waiting for database...` until it finally times out.

I dug around in the code, and the command to decide if database is up is the following:
```
db_is_up() {
    nc -z "${DATABASE_HOST:-database}" "${DATABASE_PORT:-3306}" >/dev/null 2>&1
}
```

I tried running `nc -z "localhost" "3306"` and it returns `Connection to localhost port 3306 [tcp/mysql] succeeded!`. Not sure what I am doing wrong, any advise is appreciated.
