### ISSUE TITLE
Providing AUTH_OKTA_* env vars does not display login with Okta

### ISSUE THREAD

**Issue by kurnifamili** [directus/docker#29]
Hi guys,
I have provided the following environment variables in my `docker-compose.yml` file.
```
api:
    image: directus/api:2.0.17
    environment:
      AUTH_OKTA_CLIENT_ID: "some-client-id"
      AUTH_OKTA_CLIENT_SECRET: "some-client-secret"
      AUTH_OKTA_BASE_URL: "some-base-url"
    ports:
      - 7000:80
```
But my login page still does not show any login with Okta option. Did I miss any other configurations?
