### ISSUE TITLE
docker-compose dev setup for extentions or Dockfile template

### ISSUE THREAD

**Issue by argmhz** [directus/docker#31]
Hi, I'm new to this :) 

I'm struggling with a way to make new extentions to the app (api). But it is a little hard because i'm only using docker, to not make my laptop "dirty".  
Please correct me if im wrong, but I can't seem to find an easy way but clone the Api repo and build up an Dockerfile of my own. ( maybe a guide on that? ) 
It could be nice to have a Dockerfile template or something like that, to get up and running. 

Thanks :)

**Comment by mvhirsch** [comment]
Hi @argmhz,

if you're already using a docker-compose.yaml, you could simple mount a volume (I'm using https://github.com/directus/docker/blob/master/examples/single-api/docker-compose.yml as origin):

```
services:
    
    # ...

    api:
        # ...
        volumes: 
            - ./custom:/var/www/html/public/extensions/custom
```

This way your local folder named _costum_ will be mounted inside the Docker environment. You can then build your extensions/hooks/interfaces and so on.
Just make sure, to take a look into the directory structure first: https://github.com/directus/api/tree/master/public/extensions/custom

Hope this helps!
