### ISSUE TITLE
HTTP 405 given when logging in

### ISSUE THREAD

**Issue by jnsvd** [directus/docker#42]
I'm getting the following when logging in in the `directus/app` container (from the browser):

```
10.240.0.36 - - [08/May/2019:10:55:38 +0000] "POST /auth/authenticate HTTP/1.1" 405 173 "http://<redacted>" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15" "10.240.0.97"
```

I tried various options for `API_ENDPOINT` variable, but it seems the `app` container itself is returning the 405 and no connection with the `api` container is yet initiated.

The following value is configured in `API_ENDPOINT`:
```
/ # printenv | grep ENDPOINT
API_ENDPOINT=API; http://<redacted>-directus-api.<redacted>.nip.io:80/_/
```

However, when logging in, a request is sent to a different endpoint:

```
Summary
URL: http://<redacted>-directus-app.<redacted>.nip.io/auth/authenticate
Status: 405 Not Allowed
Source: Network
Address: <redacted>:80

Request
POST /auth/authenticate HTTP/1.1
Cookie: intercom-id-f1veohy3=1dd60614-4555-4e2f-b14d-50cdeeece046; _ga=GA1.2.2096097038.1557159154; _gid=GA1.2.1744702822.1557159154
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=UTF-8
Origin: http://<redacted>-directus-app.<redacted>.nip.io
Content-Length: 60
Accept-Language: en-us
Host: <redacted>-directus-app.<redacted>.nip.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15
Referer: http://<redacted>-directus-app.<redacted>.nip.io/
Accept-Encoding: gzip, deflate
Connection: keep-alive

Response
HTTP/1.1 405 Not Allowed
Date: Wed, 08 May 2019 12:03:00 GMT
Content-Length: 173
Connection: keep-alive
Content-Type: text/html
Server: nginx/1.15.8

Request Data
MIME Type: application/json
Encoding: UTF-8
Request Data: 
```

`directus/api` version: 2.0.18
`directus/app` version: 7.0.18

**Comment by am-webdev** [comment]
Hi @jnsvd  Could you provide the docker-compose file? I've had the same issue but it was an user related issue for me :D maybe I can help you out

**Comment by TargetTaiga** [comment]
I'm also getting 405 on login attempt

```
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  directus:
    image: directus/app
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: example
      ADMIN_EMAIL: admin
      ADMIN_PASSWORD: example
    ports:
      - 8090:80

```

**Comment by jishi** [comment]
Did anyone figure out what the reason for this is? I can't seem to find any logs that can tell me why this is happening. My compose file looks like this:

```
version: '3'
services:
  api:
    image: directus/api
    links:
    - mysql
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_USERNAME: 'user'
      DATABASE_PASSWORD: 'password'
      ADMIN_EMAIL: 'test@example.org'
    ports:
      - 80
  app:
    image: directus/app
    ports: 
      - '8080:80'
    links: 
      - api
    environment:
      API_ENDPOINT: 'API; http://api/_/'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'directus'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
```

`wget http://api/_/` works from the app container and gives me `{"data":{"api":{"project_name":"Directus","project_logo":""}},"public":true}` as a response.

But the web UI keep sending requests to  
`app_1    | 172.20.0.1 - - [18/Jun/2019:07:59:24 +0000] "POST /auth/authenticate HTTP/1.1" 405 575 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-`

And no requests reach the API container.

**Comment by jishi** [comment]
Never mind, just realized that the browser needs to access the API directly, not the app container. This setup would work:

```
version: '3'
services:
  api:
    image: directus/api
    links:
    - mysql
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_USERNAME: 'user'
      DATABASE_PASSWORD: 'password'
      ADMIN_EMAIL: 'test@example.org'
    ports:
      - '8090:80'
  app:
    image: directus/app
    ports: 
      - '8080:80'
    environment:
      API_ENDPOINT: 'API; http://localhost:8090/_/'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'directus'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
```
