### ISSUE TITLE
Found + fixed issue with installer script

### ISSUE THREAD

**Issue by Ron-Kuper-Bose** [directus/docker#66]
Hello,

I've been struggling with getting the installer script to run - it was hanging and/or creating the wrong password.

It seems `api-entrypoint` uses the following code to generate a random password if none was supplied:
`cat /dev/random | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1`

On my EC2 instance this would hang (/dev/random would hang). I replaced it with the following, and solved my problem:
`head -c 1024 /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1`

**Comment by WoLfulus** [comment]
I did merge a PR fixing that #65 

Should be up in the next release :)

**Comment by TonyEight** [comment]
Waiting for the release, you can still set up your own `api-entrypoint` file by copying the one in this repo and replacing line 13 according to your needs. Mine just looks like this: 

`install_password=$(argument password "${DIRECTUS_INSTALL_PASSWORD:-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1)}")`

Make the file executable : `chmod +x`

And link it in your `docker-compose.yml` file:

```
  installer:
    image: directus/api:latest
    restart: "no"
    # True because this is not meant to run automatically.
    # Setting to true makes it exit successfully on `docker-compose up`
    command: "true"
    volumes:
      - ./api-entrypoint:/usr/local/bin/api-entrypoint
    environment:
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "root"
      DIRECTUS_DATABASE_PASSWORD: "directus"
```
