### ISSUE TITLE
When DIRECTUS_USE_ENV=0, Container Should Not Require DIRECTUS_AUTH_* Variables

### ISSUE THREAD

**Issue by mikylebaksh** [directus/docker#73]
If I choose to configure Directus by using the `api.php` configuration file, I can set an environment variable in my docker-compose as follows: `DIRECTUS_USE_ENV=0`. However, the docker/api container requires variables `DIRECTUS_AUTH_PUBLICKEY` and `DIRECTUS_AUTH_SECRETKEY` to be set even though these configuration options will come from `api.php`.

If `DIRECTUS_USE_ENV=0`, then the container should start without the `DIRECTUS_AUTH_*` variables.

See example docker-compose file for the setup I'm using

```  yaml
version: "3"
services:
#
  # API instance.
  # This should serve our api requests and won't work before database
  # is properly installed by running the installer.
  #
  api:
    image: directus/api:v2-apache
    ports:
      - "8080:80"
    environment:
      # App
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_APP_TIMEZONE: "America/Sao_Paulo"

      # Turn configuration by environment variables
      DIRECTUS_USE_ENV=0

      # These are required, even though api.php's values will override
      # any value placed here
      DIRECTUS_AUTH_PUBLICKEY: "some random secret"
      DIRECTUS_AUTH_SECRETKEY: "another random secret"

      # Database
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "directus"
      DIRECTUS_DATABASE_PASSWORD: "directus"
    links:
      - mysql:mysql
```
