### ISSUE TITLE
API Works, But Logging Into App Creates a "Server Error"

### ISSUE THREAD

**Issue by zfalen** [directus/docker#75]
Submitting this as a separate issue from the auto-install / CI issue posted earlier, as I think they are separate. Feel free to have me merge them or to move this one to the `directus/app` repo if it makes more sense there. 

I have the Directus API stood up and alive, deployed to cloud host via our CI and Rancher. I _did_ use our custom auto-install logic for this, but it appears to have worked out just fine _(e.g. waited until the DB was initialized, ran the install script, and output the right confirmation dialog)._

Here is what came back after install _(which indicates it worked just fine):_
```
10/29/2019 3:32:12 PM Waiting for local MySQL DB to stand up...
10/29/2019 3:32:17 PM mysqld is alive
10/29/2019 3:32:17 PM MySQL DB is up - moving on
10/29/2019 3:32:17 PM Installing database...
10/29/2019 3:32:18 PM Registering user...
10/29/2019 3:32:18 PM -------------------------------------------------------------
10/29/2019 3:32:18 PM
10/29/2019 3:32:18 PM  Tool Suite - Some Cool App installation completed, you can now
10/29/2019 3:32:18 PM  login with the following credentials:
10/29/2019 3:32:18 PM
10/29/2019 3:32:18 PM      Email: admin@admin.com
10/29/2019 3:32:18 PM      Password: admin
10/29/2019 3:32:18 PM
10/29/2019 3:32:18 PM -------------------------------------------------------------
10/29/2019 3:32:18 PM AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.179.53. Set the 'ServerName' directive globally to suppress this message
10/29/2019 3:32:18 PM AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.179.53. Set the 'ServerName' directive globally to suppress this message
10/29/2019 3:32:18 PM [Tue Oct 29 22:32:18.691684 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.10 configured -- resuming normal operations
10/29/2019 3:32:18 PM [Tue Oct 29 22:32:18.692933 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Obviously, there's some `echo` action going on above that I added as part of the custom fork _(basically just pinging the DB with `mysqladmin` until it's ready to accept connections)_ but otherwise the install script is completely normal.

Using Postman, I can connect to this API instance with a `POST` at `http://the-hosted-api-url.ourserver.xyz/_/auth/authenticate` with the admin credentials above and generate an auth token successfully per the docs. Then, I can use the token to access all the normal endpoints. Of course, this is a 100% fresh DB install so there's no new data in there to dig through, but I imagine I could retrieve it just fine. 

However, when I use the Directus App to connect to this URL, **I am able to log in with the admin creds** then end up with this screen:
<img width="1552" alt="Screen Shot 2019-10-29 at 3 46 51 PM" src="https://user-images.githubusercontent.com/14879054/67815667-cf1d7a80-fa64-11e9-8ec2-6a5a942f5b70.png">
 
Strange. This is reproducible on _both_ the hosted version of the App I pushed via our CI and on a local version I can stand up on my machine to hit the same hosted API URL. I am getting _no_ errors in the console in either case. Or, inside of the DB or API containers, for that matter. 

Versioning things worth noting:

1. The API image we are using implements custom logic I've described in the other issue I posted, but it really just waits until the DB is ready, then runs the `install` command. That command itself is not modified. Also it volumes a `.dbInstalled` file to prevent it from running again. **However, this image is based on the most recent commit to the `develop` branch of the API** in order to address the issue identified here until the next release: https://github.com/directus/api/issues/1337 _(otherwise the API was failing to install **on our CI** with that ENV variables error. It still worked locally without using the `develop` branch.)_

2. The App image is `directus/app:v7-node` and not modified in any way. However we have it hosted in a separate Rancher stack to theoretically manage lots of API instances as we stand them up. 

3. The DB is a hosted version of `mysql:5.7` with a volume set up to persist data. _(although we will probably switch to a DBaaS eventually)_

Here is the relevant `docker-compose.yml` for the API stack:
  ```
  # Directus API instance.
  directus-api:
    image: ourDockerHub/ourForkedDirectusAPI:latest
    ports:
      - "8080:80"
    # This is where the .dbInstalled file lives
    volumes:
      - "${PWD}/../bin/installConfig:/var/www/public/installConfig"
    environment:
      # Directus App 
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_APP_TIMEZONE: "America/San_Francisco"

      # These are now required, make sure to always set
      # to something unique while in production
      DIRECTUS_AUTH_PUBLICKEY: "awesomesauce"
      DIRECTUS_AUTH_SECRETKEY: "superDuperSecretSauce"

      # Directus Database
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "admin" 
      DIRECTUS_DATABASE_PASSWORD: "superCoolPassword"
      
      # Directus Install Setup
      DIRECTUS_INSTALL: "auto"
      DIRECTUS_INSTALL_TITLE: "Tool Suite - Some Cool App"
      DIRECTUS_INSTALL_EMAIL: "admin@admin.com"
      DIRECTUS_INSTALL_PASSWORD: "admin"
    links:
      - directus-mysql:mysql

  # Directus Database 
  directus-mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "superCoolPassword"
      MYSQL_ROOT_PASSWORD: "directus"
    volumes:
      - "${PWD}/../bin/database:/var/lib/mysql"
```

And, here is the `docker-compose.yml` for the App instance:
 ```
  # Directus APP instance.
  directus-app:
    image: directus/app:v7-node
    ports:
      - "8090:80"
    environment:
      # Endpoints
      DIRECTUS_TEAMINITIATIVES_TITLE: "Tool Suite - Some Cool App"
      DIRECTUS_TEAMINITIATIVES_URL: "http://the-hosted-api-url.ourserver.xyz/_/"

      DIRECTUS_ALLOW_OTHER_API: "true"
```
