### ISSUE TITLE
Can't set api url in app container anymore

### ISSUE THREAD

**Issue by glappsi** [directus/docker#77]
I am using the `directus/app:latest`. Until a few weeks ago I was able to set the api url by using the following env variable: `API_ENDPOINT: "API; <URL>/_/"`. This does not work anymore, since  the `config.js` requests fails. I have to set the url in the ui for each login.

I tested it with `directus/app:7.0.18`, this works.

Is it a bug or did the environment variable name change?

**Comment by ThaDaVos** [comment]
Same here - any solution? We've got three instances of the API (2 with the same versions and 1 a bit older) and we would like to manage them all from the same Client instance

**Comment by nachogarcia** [comment]
We're using the following configmap and works flawlessly
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: directus-app-configmap
data:
  DIRECTUS_DEV_TITLE: "DEV"
  DIRECTUS_DEV_URL: "https://dev.company.private/_/"
  DIRECTUS_QA_TITLE: "QA"
  DIRECTUS_QA_URL: "https://qa.company.private/_/"
```

Check the variable names.
