### ISSUE TITLE
"Couldn't reach API" on clean docker install.

### ISSUE THREAD

**Issue by artur-shaik** [directus/docker#94]
Here is my docker-compose:

```yaml
directus:
  image: directus/directus:v8-apache
  container_name: directus
  ports:
    - "43893:80"
  environment:
    # App
    DIRECTUS_ENV: "production"

    # These are now required, make sure to always set
    # to something unique while in production
    DIRECTUS_AUTH_PUBLICKEY: "ohraeP9geesahb1teik8AhY'ohwu8ooj"
    DIRECTUS_AUTH_SECRETKEY: "cieg8fa0eing:ea_Qu9omai1UN9gohte"

    # Database
    DIRECTUS_DATABASE_HOST: "172.17.0.1"
    DIRECTUS_DATABASE_PORT: "3306"
    DIRECTUS_DATABASE_NAME: "directus_01"
    DIRECTUS_DATABASE_USERNAME: "directus"
    DIRECTUS_DATABASE_PASSWORD: "pwd"

  volumes:
    - ./data/config:/var/directus/config
    - ./data/uploads:/var/directus/public/uploads
```

If I enter wrong username or password it shows: `Incorrect Email/Password`. But if I enter existed user credentials it shows: `Couldn't reach API`

No errors in `docker-compose up` logs.

So, the question is, where I can find debug information to find out where is problem?
